apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: odoo
  labels:
    app: odoo
spec:
  ports:
    - port: 8069
      name: odoo
    - port: 5432
      name: postgres
  type: LoadBalancer
  selector:
    app: odoo
